### ISSUE TITLE
Outbound emails not working on Staging and Production instances

### ISSUE THREAD

**Issue by brittyazel** [canonical/indico-operator#110]
### Bug Description

Testing the production and staging instances for Indico, I'm not seeing any outbound emails making it to their destination. I sent a couple of quick test emails from the staging instance to both Varshi and my email addresses, and neither of them arrived. I'm hoping this is just an smtp configuration issue, perhaps the logs can point out what is going on.

The upstream documentation for email configuration can be found here:
https://docs.getindico.io/en/latest/config/settings/#emails

### To Reproduce

The easiest way I've found to send a direct email is to:

1) Go to the admin panel of a given event
2) Under Organization>Reminders click "Add Reminder"
3) Choose "Send Immediately" and enter the addresses of your email recipients
4) Hit Save

### Environment

I'm using the deployed instance at events.canonical.com and events.staging.canonical.com

### Relevant log output

```shell
n/a
```

**Comment by kewisch** [comment]
I see this as well for example in the "add email address" mask in the profile.

**Comment by arturo-seijas** [comment]
You can expect this change to land today in production.

Thank you for the feedback.
