### ISSUE TITLE
Caching makes it appear as if settings are not changed

### ISSUE THREAD

**Issue by kewisch** [canonical/indico-operator#111]
### Bug Description

There seem to be some caching issues when making changes to settings

### To Reproduce

1. Set up a profile on indico
2. Go to the profile picture section
3. Switch from system-generated to another option, e.g. gravatar
4. Save

Result:
* The avatar is changed successfully to gravatar
* "system-generated" is still highlighted, as if that were still the value

Expected:
* The avatar is changed successfully to gravatar
*  The gravatar option is highlighted

### Environment

events.canonical.com

### Relevant log output

```shell
no logs
```

### Additional context

A hard refresh will "fix" this. The same happens for a bunch of other settings, such as making someone an admin and them not appearing in the list.

**Comment by mthaddon** [comment]
Confirmed this has been fixed. We're still working on a better caching set up (specifically making sure static resources that can be cached for logged in users are cached), but I'll close this out for now as that's being handled separately.
