### ISSUE TITLE
Prod and Staging websites are not updating customization assets upon new commits

### ISSUE THREAD

**Issue by brittyazel** [canonical/indico-operator#120]
### Bug Description

I was told that Prod and Staging would be checking for new updates to the canonical-indico-customization-files repo, and would pull in new changes every 2-5min. That does not appear to be the case, and I have new commits in that repo that are not reflected on either Staging or Prod.

### To Reproduce

1) Push a new commit to https://github.com/canonical/canonical-indico-customization-files
2) Confirm after many minutes that the changes aren't being pulled in

### Environment

N/A

### Relevant log output

```shell
N/A
```

**Comment by arturo-seijas** [comment]
Staging should be fixed by now. Can you double check?

**Comment by varshigupta12** [comment]
@brittyazel Can you please test this bug and let us know if we can close it?
