### ISSUE TITLE
Error when uploading images through the Image Manager

### ISSUE THREAD

**Issue by brittyazel** [canonical/indico-operator#121]
### Bug Description

When trying to upload a picture into the image manager for an event, I get the following error:
```
Something went wrong
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

I was trying to attach the following image to be used on a page talking about Prague:
![basi_info_large](https://user-images.githubusercontent.com/3747347/188522858-c0a0051d-f814-48b6-8563-e23ab8c5e0db.jpg)

### To Reproduce

1) Go the admin panel for an event
2) Go to Customization > Images
3) Attempt to upload an image

### Environment

N/A

### Relevant log output

```shell
N/A
```

**Comment by arturo-seijas** [comment]
Fixed. Some settings were misconfigured.
