### ISSUE TITLE
Increase timeout for email and import endpoints

### ISSUE THREAD

**Issue by kewisch** [canonical/indico-operator#242]
### Bug Description

I mentioned this on MM, but filing here to track it somewhere. The following URLs have a 504 gateway timeout, though they are long running operations. This causes some undefined errors in Indico which causes emails to be sent many times, or a potentially incomplete import operation.

POST https://events.canonical.com/event/NNN/manage/registration/NNN/registrations/email 

POST https://events.canonical.com/event/NNN/manage/registration/NNN/registrations/import

If you could bump the timeout for this to several minutes this would be helpful.

### To Reproduce

One simple way to test this is to import >500 users into an event registration using CSV.

### Environment

events.canonical.com
events.staging.canonical.com

### Relevant log output

```shell
--
```

### Additional context

Once changed, we should confirm this works as expected, I'm not sure if there is also a client side read timeout involved in addition. The message I get is definitely server side though.

**Comment by amandahla** [comment]
The timeout was changed for:
```
POST https://events.staging.canonical.com/event/NNN/manage/registration/NNN/registrations/email 
POST https://events.staging.canonical.com/event/NNN/manage/registration/NNN/registrations/import
```
Test: 800 participants were successfully imported.
