### ISSUE TITLE
Indico v3.3 - planned changes to our Docker image

### ISSUE THREAD

**Issue by ThiefMaster** [canonical/indico-operator#256]
Hey, just a heads-up: For Indico v3.3 we plan to make some changes to our docker images.

The most important one is probably that we want to ditch the (somewhat messy) env vars used for indico.conf in favor of providing a full indico.conf: https://github.com/indico/indico-containers/pull/28

We might also move from Docker Hub to GHCR since everything else is on GitHub as well, and even though Docker Inc backpedaled on the "Free Team" change, we think it's likely safer to not depend on Docker Hub...

cc @tomasr8

**Comment by arturo-seijas** [comment]
Thanks for letting us know
