### ISSUE TITLE
Switch Indoco from legacy PostgreSQL interface to the modern one

### ISSUE THREAD

**Issue by taurus-forever** [canonical/indico-operator#436]
### Enhancement Proposal

Hi,

The modern PostgreSQL charms support both legacy and modern interfaces,
more details in: https://charmhub.io/postgresql-k8s/docs/e-legacy-charm

As we can see from the [tutorial](https://charmhub.io/indico/docs/tutorial) the Indico charm is still using legacy interface:
> juju integrate indico postgresql-k8s:db

This is a feature request to migrate Indico charm  to the modern interface.
It should be straightforward and we have prepared the How-to for you:
https://charmhub.io/postgresql-k8s/docs/h-integrate-with-your-charm

The legacy interface will be removed from the next PostgreSQL 16 charm (24.04 based),
it is good to migrate to the new interface now without rush. You are using PostgreSQL 14 (22.04 based).

Feel free to ping us if you have any questions or need an assist.
Thank you!

**Comment by taurus-forever** [comment]
Oh, it could be just a documentation issue, as I see the modern [postgresql_client interface in use](https://github.com/canonical/indico-operator/blob/main/metadata.yaml#L56C16-L56C33).

**Comment by cbartz** [comment]
The tutorial on charmhub is out of date (but the source on github is up to date). @alithethird Can you please sync the docs on git with the ones on charmhub? This is normally done automatically when promoting the charm rev to stable (but maybe configured differently here).

**Comment by alithethird** [comment]
Updated the charmhub documentation to the latest version in GitHub.
