### ISSUE TITLE
Perform initial configuration currently done manually via /bootstrap in the UI

### ISSUE THREAD

**Issue by mthaddon** [canonical/indico-operator#76]
Currently when you first deploy indico the first visitor to the site is redirected to `/bootstrap` and asked to enter some initial admin details.

The charm should automate this for us, exposing configuration options for relevant choices where appropriate.

**Comment by arturo-seijas** [comment]
@mthaddon I this has been addressed by https://github.com/canonical/indico-operator/pull/220. I'm closing the issue
